// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSZvUqAQflG9HbBQ6-L0srPgrjwWJ6W8o',
    appId: '1:751562297279:web:574ec876cbc0b3feda1b0a',
    messagingSenderId: '751562297279',
    projectId: 'matbucks-erp',
    authDomain: 'matbucks-erp.firebaseapp.com',
    storageBucket: 'matbucks-erp.appspot.com',
    measurementId: 'G-S2GQ3CTW4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWAHQzDGaGJIeQ4dl88nNXuAMkbj9F_jE',
    appId: '1:751562297279:android:b70ef7e582210cb2da1b0a',
    messagingSenderId: '751562297279',
    projectId: 'matbucks-erp',
    storageBucket: 'matbucks-erp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ztJq73RrcVsKs8a6AkN64RaJRNoj8wc',
    appId: '1:751562297279:ios:b2671e301860e8a2da1b0a',
    messagingSenderId: '751562297279',
    projectId: 'matbucks-erp',
    storageBucket: 'matbucks-erp.appspot.com',
    iosBundleId: 'com.example.schoolErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ztJq73RrcVsKs8a6AkN64RaJRNoj8wc',
    appId: '1:751562297279:ios:b2671e301860e8a2da1b0a',
    messagingSenderId: '751562297279',
    projectId: 'matbucks-erp',
    storageBucket: 'matbucks-erp.appspot.com',
    iosBundleId: 'com.example.schoolErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSZvUqAQflG9HbBQ6-L0srPgrjwWJ6W8o',
    appId: '1:751562297279:web:7edd061154afb970da1b0a',
    messagingSenderId: '751562297279',
    projectId: 'matbucks-erp',
    authDomain: 'matbucks-erp.firebaseapp.com',
    storageBucket: 'matbucks-erp.appspot.com',
    measurementId: 'G-QJCB16YB2W',
  );
}
